import {
  dateAt,
  type CalendarMember,
  type SessionEvent,
} from "@/components/tenant/consultant/sessions/session-data";

// One color per consultant so events are attributable at a glance.
export const consultantMembers: CalendarMember[] = [
  { id: "all", label: "All consultants" },
  { id: "advik", label: "Advik Advik", colorClass: "bg-emerald-600" },
  { id: "wendy", label: "Wendy Smith", colorClass: "bg-violet-600" },
  { id: "ravi", label: "Ravi Sharma", colorClass: "bg-sky-600" },
  { id: "meera", label: "Meera Iyer", colorClass: "bg-rose-600" },
];

export const allConsultantEvents: SessionEvent[] = [
  {
    id: "advik-sarah-initial",
    title: "Advik · Sarah D - Initial Assessment",
    start: dateAt(1, 10, 0),
    end: dateAt(1, 11, 0),
    memberId: "advik",
    consultantName: "Advik Advik",
    clientName: "Sarah Doe",
    clientCode: "000002",
    clientStatus: "Lead",
    appointmentStatus: "Confirmed",
    paymentStatus: "Unpaid",
    serviceName: "Initial Assessment",
    serviceDuration: "60 mins",
    servicePrice: "₹150.00",
    description: "Initial Assessment with Sarah Doe",
    colorClass: "bg-emerald-600",
  },
  {
    id: "advik-john-final",
    title: "Advik · John D - Final Appointment",
    start: dateAt(1, 13, 0),
    end: dateAt(1, 13, 45),
    memberId: "advik",
    consultantName: "Advik Advik",
    clientName: "John Doe",
    clientCode: "000001",
    clientStatus: "Active",
    appointmentStatus: "Confirmed",
    paymentStatus: "Paid",
    serviceName: "Standard Appointment",
    serviceDuration: "45 mins",
    servicePrice: "₹100.00",
    description: "Final Appointment with John Doe",
    colorClass: "bg-emerald-600",
  },
  {
    id: "wendy-priya-followup",
    title: "Wendy · Priya K - Follow-up",
    start: dateAt(1, 11, 30),
    end: dateAt(1, 12, 15),
    memberId: "wendy",
    consultantName: "Wendy Smith",
    clientName: "Priya Kapoor",
    clientCode: "000005",
    clientStatus: "Active",
    appointmentStatus: "Confirmed",
    paymentStatus: "Paid",
    serviceName: "Follow-up Session",
    serviceDuration: "45 mins",
    servicePrice: "₹100.00",
    description: "Follow-up session with Priya Kapoor",
    colorClass: "bg-violet-600",
  },
  {
    id: "wendy-arjun-initial",
    title: "Wendy · Arjun M - Initial Assessment",
    start: dateAt(2, 9, 30),
    end: dateAt(2, 10, 30),
    memberId: "wendy",
    consultantName: "Wendy Smith",
    clientName: "Arjun Mehta",
    clientCode: "000006",
    clientStatus: "Lead",
    appointmentStatus: "Pending",
    paymentStatus: "Unpaid",
    serviceName: "Initial Assessment",
    serviceDuration: "60 mins",
    servicePrice: "₹150.00",
    description: "Initial Assessment with Arjun Mehta",
    colorClass: "bg-violet-600",
  },
  {
    id: "ravi-neha-standard",
    title: "Ravi · Neha G - Standard Appointment",
    start: dateAt(2, 14, 0),
    end: dateAt(2, 14, 45),
    memberId: "ravi",
    consultantName: "Ravi Sharma",
    clientName: "Neha Gupta",
    clientCode: "000007",
    clientStatus: "Active",
    appointmentStatus: "Confirmed",
    paymentStatus: "Paid",
    serviceName: "Standard Appointment",
    serviceDuration: "45 mins",
    servicePrice: "₹100.00",
    description: "Standard appointment with Neha Gupta",
    colorClass: "bg-sky-600",
  },
  {
    id: "ravi-vikram-review",
    title: "Ravi · Vikram S - Treatment Review",
    start: dateAt(3, 10, 0),
    end: dateAt(3, 11, 0),
    memberId: "ravi",
    consultantName: "Ravi Sharma",
    clientName: "Vikram Singh",
    clientCode: "000008",
    clientStatus: "Active",
    appointmentStatus: "Confirmed",
    paymentStatus: "Unpaid",
    serviceName: "Treatment Review",
    serviceDuration: "60 mins",
    servicePrice: "₹120.00",
    description: "Treatment review with Vikram Singh",
    colorClass: "bg-sky-600",
  },
  {
    id: "meera-ananya-initial",
    title: "Meera · Ananya R - Initial Assessment",
    start: dateAt(3, 15, 0),
    end: dateAt(3, 16, 0),
    memberId: "meera",
    consultantName: "Meera Iyer",
    clientName: "Ananya Rao",
    clientCode: "000009",
    clientStatus: "Wait List",
    appointmentStatus: "Pending",
    paymentStatus: "Unpaid",
    serviceName: "Initial Assessment",
    serviceDuration: "60 mins",
    servicePrice: "₹150.00",
    description: "Initial Assessment with Ananya Rao",
    colorClass: "bg-rose-600",
  },
  {
    id: "meera-karan-followup",
    title: "Meera · Karan P - Follow-up",
    start: dateAt(4, 11, 0),
    end: dateAt(4, 11, 45),
    memberId: "meera",
    consultantName: "Meera Iyer",
    clientName: "Karan Patel",
    clientCode: "000010",
    clientStatus: "Active",
    appointmentStatus: "Confirmed",
    paymentStatus: "Paid",
    serviceName: "Follow-up Session",
    serviceDuration: "45 mins",
    servicePrice: "₹100.00",
    description: "Follow-up session with Karan Patel",
    colorClass: "bg-rose-600",
  },
  {
    id: "advik-sarah-followup",
    title: "Advik · Sarah D - Follow-up",
    start: dateAt(4, 16, 0),
    end: dateAt(4, 16, 45),
    memberId: "advik",
    consultantName: "Advik Advik",
    clientName: "Sarah Doe",
    clientCode: "000002",
    clientStatus: "Lead",
    appointmentStatus: "Pending",
    paymentStatus: "Unpaid",
    serviceName: "Follow-up Session",
    serviceDuration: "45 mins",
    servicePrice: "₹100.00",
    description: "Follow-up session with Sarah Doe",
    colorClass: "bg-emerald-600",
  },
];
