import type { TourStep } from "../types";

export const consultantTourSteps: TourStep[] = [
  {
    target: '[data-tour="consultant-sidebar"]',
    route: "/dashboard",
    title: "Welcome",
    content:
      "Your morning briefing: today's appointments, critical commitments, priority tasks, and AI summary.",
    placement: "right",
  },
  {
    target: '[data-tour="consultant-morning-brief"]',
    route: "/dashboard",
    title: "Today's Briefing",
    content: "What needs your attention today. Updates throughout the day.",
    placement: "bottom",
  },
  {
    target: '[data-tour="consultant-daily-timeline"]',
    route: "/dashboard",
    title: "Daily Timeline",
    content: "Visual heatmap of booked vs available slots across the coming weeks.",
    placement: "bottom",
  },
  {
    target: '[data-tour="consultant-critical-commitments"]',
    route: "/dashboard",
    title: "Critical Commitments",
    content: "Overdue or due-soon commitments. Click to jump to the case.",
    placement: "left",
  },
  {
    target: '[data-tour="consultant-nav-cases"]',
    route: "/cases",
    title: "Your Cases",
    content: "All cases assigned to you. Each has a chronological timeline.",
    placement: "right",
  },
  {
    target: '[data-tour="consultant-case-timeline"]',
    route: "/cases/:id",
    title: "Case Timeline",
    content:
      "The core of Ayushman — sessions, notes, commitments, tasks, documents in one chronological feed. Filter, search, and add entries inline.",
    placement: "top",
  },
  {
    target: '[data-tour="consultant-quick-capture"]',
    title: "Quick Capture",
    content:
      "This floating button lets you log a note, call, or message from any page. Works offline too.",
    placement: "left",
  },
  {
    target: '[data-tour="consultant-nav-clients"]',
    route: "/clients",
    title: "Client Directory",
    content: "Search, pin, filter by deadline. Book appointments directly from here.",
    placement: "right",
  },
  {
    target: '[data-tour="consultant-nav-availability"]',
    route: "/availability",
    title: "Availability",
    content: "Set weekly hours and block specific dates. This controls when clients can book you.",
    placement: "right",
  },
  {
    target: '[data-tour="consultant-nav-appointments"]',
    route: "/appointments",
    title: "Appointment Queue",
    content: "Admin-approved requests appear here. Accept or propose a reschedule.",
    placement: "right",
  },
  {
    target: '[data-tour="consultant-nav-templates"]',
    route: "/templates",
    title: "Templates",
    content: "Reusable message templates (email) and form templates. Create once, use everywhere.",
    placement: "right",
  },
  {
    target: '[data-tour="consultant-templates-board"]',
    route: "/templates",
    title: "Templates Board",
    content:
      "Board view of all your templates. Create new ones with the + button. Filter by type: message or form.",
    placement: "top",
  },
  {
    target: '[data-tour="consultant-nav-workflows"]',
    route: "/workflows",
    title: "Workflows",
    content:
      "Automate repetitive tasks. Trigger actions when cases are created, appointments booked, or sessions complete.",
    placement: "right",
  },
  {
    target: '[data-tour="consultant-workflows-board"]',
    route: "/workflows",
    title: "Workflows Board",
    content:
      "Your personal workflows. Create new ones, view run history, and toggle active/inactive.",
    placement: "top",
  },
  {
    target: '[data-tour="consultant-nav-referrals"]',
    route: "/referrals",
    title: "Referrals",
    content:
      "Cases colleagues send you, and cases you refer out. Track status and view the read-only case.",
    placement: "right",
  },
  {
    target: '[data-tour="consultant-nav-calendar"]',
    route: "/calendar",
    title: "Your Calendar",
    content: "A calendar view of every appointment on your books.",
    placement: "right",
  },
  {
    target: '[data-tour="consultant-nav-inbox"]',
    route: "/inbox",
    title: "Inbox",
    content: "Connect your email to see client conversations alongside your cases.",
    placement: "right",
  },
  {
    target: '[data-tour="consultant-nav-team"]',
    route: "/team",
    title: "Your Team",
    content: "See peer consultants in this practice and their current status.",
    placement: "right",
  },
  {
    target: '[data-tour="consultant-nav-billing"]',
    route: "/billing",
    title: "Billing",
    content: "Invoices, payments, and payouts for your client roster.",
    placement: "right",
  },
  {
    target: '[data-tour="consultant-nav-documentation"]',
    route: "/documentation",
    title: "Documentation",
    content: "Documents, form submissions, and shared templates, organized by case.",
    placement: "right",
  },
  {
    target: '[data-tour="consultant-nav-help"]',
    route: "/help",
    title: "Help",
    content: "Guides, FAQs, and support contacts.",
    placement: "right",
  },
  {
    target: '[data-tour="consultant-nav-notifications"]',
    route: "/notifications",
    title: "Notifications",
    content: "Choose how you hear about appointments, tasks, and more.",
    placement: "right",
  },
  {
    target: '[data-tour="consultant-nav-settings"]',
    route: "/settings",
    title: "Settings",
    content: "Your profile, verification documents, and out-of-office schedule.",
    placement: "right",
  },
  {
    target: '[data-tour="consultant-appointment-detail"]',
    route: "/appointments/:id",
    title: "Appointment Detail",
    content: "Accept, propose a reschedule, mark complete/no-show, or transfer to a colleague.",
    placement: "top",
  },
  {
    target: '[data-tour="consultant-new-case-form"]',
    route: "/cases/new",
    title: "New Case",
    content: "Add a client, attach documents, and start tracking the case.",
    placement: "top",
  },
  {
    target: '[data-tour="consultant-referral-detail"]',
    route: "/referrals/:id",
    title: "Referral Detail",
    content: "Review context, accept or decline, and see the read-only case handed to you.",
    placement: "top",
  },
  {
    target: '[data-tour="consultant-session-recording"]',
    route: "/sessions/:appointmentId",
    title: "Session Recording",
    content: "Record, transcribe, and generate notes right from the session.",
    placement: "top",
  },
  {
    target: '[data-tour="consultant-form-builder"]',
    route: "/templates/forms/new",
    title: "Form Builder",
    content:
      "Drag in fields, set validation, and publish a form clients fill out from their portal.",
    placement: "top",
  },
  {
    target: '[data-tour="consultant-workflow-canvas"]',
    route: "/workflows/:workflowId",
    title: "Workflow Canvas",
    content: "Wire up triggers, conditions, and actions visually.",
    placement: "top",
  },
  {
    target: '[data-tour="consultant-workflow-runs"]',
    route: "/workflows/:workflowId/runs",
    title: "Run History",
    content: "See every execution of this workflow, with status and timing.",
    placement: "top",
  },
];
